- platform: worxlandroid
  host: 192.168.2.4
  pin: 9904

- platform: rest
  name: External IP
  resource: https://api.ipify.org
  method: GET
  scan_interval: 300  # uppdateras var 5:e minut
  value_template: "{{ value }}"
